#!/usr/bin/env bash
# flush_artifacts.sh — reclaim QA run artifacts: every qa_output/<script> dir
# (screenshots, events.jsonl, result.json) and any leftover per-run isolated
# HOMEs under the repo-root .godot_home/ (run_qa.sh now removes its own on
# exit, but killed/hung runs still leave them behind).
#
# Safe to run any time: everything it deletes is regenerated by the next QA
# run. ci_sweep.sh calls this at startup, so a full sweep always starts from
# a clean slate; run it manually between milestones if qa_output balloons.
# CONSTRAINT: a .godot_home/qa-<script>-<pid> dir whose pid is still ALIVE
# belongs to an in-flight run (the per-PID isolation contract in
# run_qa.sh) -- skipping those keeps concurrent runs safe; their dirs are
# removed by their own EXIT trap. qa_output/<script> dirs of live runs are
# recreated by the run itself (run_qa.sh mkdirs OUT before launch, and the
# driver re-creates it at screenshot time), so the flush only costs a live
# run its already-written artifacts, never a crash -- still: prefer not to
# flush mid-run.
set -u
PROJ="$(cd "$(dirname "$0")/.." && pwd)"
REPO_ROOT="$(cd "$PROJ/.." && pwd)"
rm -rf "$PROJ/qa_output"
for d in "$REPO_ROOT/.godot_home"/qa-*; do
	[ -e "$d" ] || continue
	pid="${d##*-}"
	if [[ "$pid" =~ ^[0-9]+$ ]] && kill -0 "$pid" 2>/dev/null; then
		echo "skip (live run, pid $pid): $d"
		continue
	fi
	rm -rf "$d"
done
mkdir -p "$PROJ/qa_output"
echo "flushed: $PROJ/qa_output/* and stale $REPO_ROOT/.godot_home/qa-*"
