#!/usr/bin/env python3
"""Generate a metadata index of potential_assets/ PNGs without opening them visually.

Parses PNG IHDR headers (stdlib only — no Pillow) for dimensions, guesses
frame counts for -Sheet.png strips from the square-frame convention
(height == frame size, width % height == 0), and writes:
  - docs/asset-index.json  (machine-readable, full)
  - docs/asset-index.md    (human/agent-readable summary, grouped by pack)

The PNGs themselves are license-bound (no redistribution) and gitignored;
this metadata index is text-only and safe to commit. Visual descriptions are
appended to the .md by a separate one-time model pass (see the "## Visual
notes" section markers) — regenerate with --keep-notes to preserve them.

Usage: python3 tools/asset_index.py [--keep-notes]
"""
from __future__ import annotations

import json
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "potential_assets"
OUT_JSON = ROOT / "docs" / "asset-index.json"
OUT_MD = ROOT / "docs" / "asset-index.md"
NOTES_MARKER = "## Visual notes"


def png_size(path: Path) -> tuple[int, int] | None:
    try:
        with path.open("rb") as f:
            head = f.read(24)
        if len(head) < 24 or head[:8] != b"\x89PNG\r\n\x1a\n" or head[12:16] != b"IHDR":
            return None
        w, h = struct.unpack(">II", head[16:24])
        return int(w), int(h)
    except OSError:
        return None


def frame_guess(name: str, w: int, h: int) -> int | None:
    """Strip sheets in these packs are horizontal runs of square frames."""
    if "sheet" not in name.lower():
        return None
    if h > 0 and w % h == 0 and w // h <= 32:
        return w // h
    return None


def build() -> dict:
    packs: dict[str, list[dict]] = {}
    for p in sorted(ASSETS.rglob("*.png")):
        rel = p.relative_to(ASSETS)
        pack = rel.parts[0]
        if pack.endswith(".zip"):
            continue
        size = png_size(p)
        if size is None:
            continue
        w, h = size
        packs.setdefault(pack, []).append({
            "path": str(rel),
            "w": w,
            "h": h,
            "frames": frame_guess(p.name, w, h),
            "bytes": p.stat().st_size,
        })
    return packs


def write_md(packs: dict, notes: str) -> None:
    lines = [
        "# potential_assets/ PNG index (generated by tools/asset_index.py)",
        "",
        "Dimensions from PNG headers; `frames` guessed for *-Sheet.png strips",
        "(width/height when frames are square). PNGs themselves are gitignored",
        "(license: no redistribution) — this index is the cheap way to browse",
        "them without loading images into model context.",
        "",
    ]
    for pack in sorted(packs):
        entries = packs[pack]
        lines.append("## %s  (%d PNGs)" % (pack, len(entries)))
        lines.append("")
        lines.append("| path | size | frames |")
        lines.append("|---|---|---|")
        for e in entries:
            fr = str(e["frames"]) if e["frames"] else ""
            lines.append("| %s | %dx%d | %s |" % (e["path"], e["w"], e["h"], fr))
        lines.append("")
    md = "\n".join(lines)
    if notes:
        md += "\n" + notes
    OUT_MD.write_text(md)


def main() -> None:
    keep_notes = "--keep-notes" in sys.argv
    notes = ""
    if keep_notes and OUT_MD.exists():
        old = OUT_MD.read_text()
        idx = old.find(NOTES_MARKER)
        if idx != -1:
            notes = old[idx:]
    packs = build()
    OUT_JSON.parent.mkdir(exist_ok=True)
    OUT_JSON.write_text(json.dumps(packs, indent=1))
    write_md(packs, notes)
    total = sum(len(v) for v in packs.values())
    print("indexed %d PNGs across %d packs -> %s, %s" % (total, len(packs), OUT_JSON, OUT_MD))


if __name__ == "__main__":
    main()
