#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from typing import Any


if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
    from scripts.itinerary.bridge import OracleBridge
    from scripts.itinerary.emit import Emitter
    from scripts.itinerary.ledger import Ledger
    from scripts.itinerary.planners.dialogue import DialoguePlanner
    from scripts.itinerary.planners.route import RoutePlanner
    from scripts.itinerary.planners.sleep import SleepPlanner
    from scripts.itinerary.schema import load_itinerary
else:
    from .bridge import OracleBridge
    from .emit import Emitter
    from .ledger import Ledger
    from .planners.dialogue import DialoguePlanner
    from .planners.route import RoutePlanner
    from .planners.sleep import SleepPlanner
    from .schema import load_itinerary


def compile_itinerary(source: Path, output: Path, project: Path, authoring: bool = False) -> dict[str, Any]:
    document = load_itinerary(source, milestone=1)
    bridge = OracleBridge(project)
    ledger = Ledger.fresh()
    script: dict[str, Any] = {
        "_comment": "Generated by scripts/itinerary/compile_itinerary.py. Edit the itinerary YAML, never this JSON.",
        "steps": [],
    }
    if document.start:
        start_path = Path(document.start)
        if not start_path.is_absolute():
            start_path = (source.parent / start_path).resolve()
        start_save = json.loads(start_path.read_text(encoding="utf-8"))
        ledger = Ledger.from_save(start_save)
        script["fixture_save"] = str(start_path)

    route = RoutePlanner(project, bridge)
    dialogue = DialoguePlanner(project, bridge, route)
    sleep = SleepPlanner(bridge)
    emitter = Emitter()
    previous_act = ""
    for node in document.nodes:
        if authoring and node.act != previous_act:
            script["steps"].append({"_itin": node.id, "action": "dump_checkpoint", "slot": f"act_{node.act}"})
        previous_act = node.act
        if node.primitive == "goto":
            cell = node.spec.get("cell")
            operations = route.plan_to(node.id, ledger, str(node.spec["map"]), cell)
        elif node.primitive == "talk":
            map_hint = str(node.spec.get("at", "")) or None
            _, entity = route.find_entity(str(node.spec["npc"]), map_hint)
            operations = dialogue.plan(node.id, node.spec, node.why, ledger, entity)
        elif node.primitive == "sleep":
            operations = sleep.plan(node.id, node.spec, ledger)
        else:
            raise RuntimeError(f"M1 compiler received unsupported primitive {node.primitive}")
        script["steps"].extend(emitter.emit(node.id, operations))

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(script, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    return script


def main() -> int:
    parser = argparse.ArgumentParser(description="Compile a Wandering Inn QA itinerary (M1)")
    parser.add_argument("itinerary", type=Path)
    parser.add_argument("--out", type=Path)
    parser.add_argument("--project", type=Path, default=Path(__file__).resolve().parents[2] / "wandering_inn_game")
    parser.add_argument("--authoring", action="store_true")
    args = parser.parse_args()
    output = args.out or args.itinerary.with_suffix(".json")
    script = compile_itinerary(args.itinerary.resolve(), output.resolve(), args.project.resolve(), args.authoring)
    raw_steps = sum(1 for step in script["steps"] if step.get("action") == "raw")
    print(f"ITINERARY_COMPILED: {output.resolve()} nodes={len(load_itinerary(args.itinerary, 1).nodes)} steps={len(script['steps'])} raw_steps={raw_steps}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

